# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Environment variables for MySQL configuration
ENV ENGINE=django.db.backends.sqlite3
ENV NAME=app_db
ENV USER=app_user
ENV PASSWORD=1234
ENV HOST=mysql
ENV PORT=3306
ENV MYSQL_ROOT_PASSWORD=1234

# Expose port 3306 for MySQL connections
EXPOSE 3306

# Set the data directory as a volume
VOLUME /var/lib/mysql